const tags = [
  {
    topic: "Life",
    subTopics: [
      {
        subTopic: "Family",
        items: [
          "Adoption",
          "Children",
          "Elder Care",
          "Fatherhood",
          "Motherhood",
          "Parenting",
        ],
      },
      {
        subTopic: "Health",
        items: [
          "Aging",
          "Coronavirus",
          "Covid-19",
          "Death And Dying",
          "Disease",
          "Fitness",
          "Mens Health",
          "Nutrition",
          "Sleep",
          "Trans Healthcare",
          "Vaccienes",
          "Weight Loss",
          "Womens Health",
        ],
      },
      {
        subTopic: "Relationships",
        items: [
          "Dating",
          "Divorce",
          "Friendship",
          "Love",
          "Marriage",
          "Poluamory",
        ],
      },
      {
        subTopic: "Home",
        items: [
          "Architecture",
          "Home Improvment",
          "Homeownership",
          "Interior Design",
          "Rental Property",
          "Vacation Rental",
        ],
      },
      {
        subTopic: "Food",
        items: ["Baking", "Cooking", "Coffee", "Foodie", "Restaurants", "Tea"],
      },
      {
        subTopic: "Pets",
        items: [
          "Cats",
          "Dogs",
          "Dog Training",
          "Horses",
          "Hamters",
          "Pet Care",
        ],
      },
    ],
  },
  {
    topic: "Self Improvement",
    subTopics: [
      {
        subTopic: "Mental Health",
        items: [
          "Anxiety",
          "Counseling",
          "Grief",
          "Life Lessons",
          "Self-awareness",
          "Stress",
          "Therapy",
          "Trauma",
        ],
      },
      {
        subTopic: "Productivity",
        items: [
          "Career Advice",
          "Coaching",
          "Goal Setting",
          "Morning Routines",
          "Pomodoro Technique",
          "Time Management",
          "Work Life Balance",
        ],
      },
      {
        subTopic: "Mindfulness",
        items: [
          "Guided Meditation",
          "Journaling",
          "Meditation",
          "Transcendental Meditation",
          "Yoga",
        ],
      },
    ],
  },
  {
    topic: "Work",
    subTopics: [
      {
        subTopic: "Business",
        items: [
          "Entrepreneurship",
          "Freelancing",
          "Small Business",
          "Startups",
          "Venture Capital",
        ],
      },
      {
        subTopic: "Marketing",
        items: [
          "Advertising",
          "Branding",
          "Content Marketing",
          "Content Strategy",
          "Digital Marketing",
          "SEO",
          "Social Media Marketing",
          "Storytelling For Business",
        ],
      },
      {
        subTopic: "Leadership",
        items: [
          "Employee Engagement",
          "Management",
          "Leadership Coaching",
          "Managment",
          "Meetings",
          "Org Charts",
          "Thought Leadership",
        ],
      },
      {
        subTopic: "Remote Work",
        items: [
          "Company Retreats",
          "Distributed Teams",
          "Wrork From Home",
          "Digital Nomads",
          "Remote Work Culture",
          "Remote Work Productivity",
          "Future Of Work",
        ],
      },
    ],
  },
  {
    topic: "Technology",
    subTopics: [
      {
        subTopic: "Artificial Intelligence",
        items: [
          "ChatGPT",
          "Conversational AI",
          "Deep Learning",
          "Large Language Models",
          "Machine Learning",
          "NLP",
          "Voice Assistance",
        ],
      },
      {
        subTopic: "Blockchain",
        items: [
          "Bitcoin",
          "Cryptocurrency",
          "Decentralized Finance",
          "Ethereum",
          "NFT",
          "Web3",
        ],
      },
      {
        subTopic: "Data Science",
        items: [
          "Analytics",
          "Data Engineering",
          "Data Visualization",
          "Database Design",
          "SQL",
        ],
      },
      {
        subTopic: "Data Science",
        items: [
          "Analytics",
          "Data Engineering",
          "Data Visualization",
          "Database Design",
          "Sql",
        ],
      },
      {
        subTopic: "Gadgets",
        items: [
          "eBook",
          "Internet of Things",
          "iPad",
          "Smart Home",
          "Smartphones",
          "Wearables",
        ],
      },
      {
        subTopic: "Makers",
        items: ["3D Printing", "Arduino", "DIY", "Raspberry Pi", "Robotics"],
      },
      {
        subTopic: "Security",
        items: [
          "Cybersecurity",
          "Data Security",
          "Encryption",
          "Infosec",
          "Passwords",
          "Privacy",
        ],
      },
      {
        subTopic: "Tech Companies",
        items: [
          "Amazon",
          "Apple",
          "Google",
          "Mastodon",
          "Medium",
          "Meta",
          "Microsoft",
          "Tiktok",
          "Twitter",
        ],
      },
      {
        subTopic: "Design",
        items: [
          "Accessibility",
          "Design Systems",
          "Design Thinking",
          "Graphic Design",
          "Icon Design",
          "Inclusive Design",
          "Product Design",
          "Typography",
          "UX Design",
          "UX Research",
        ],
      },
      {
        subTopic: "Product Management",
        items: [
          "Agile",
          "Innovation",
          "Kanban",
          "Lean Startup",
          "MVP",
          "Product",
          "Strategy",
        ],
      },
    ],
  },
  {
    topic: "Software Development",
    subTopics: [
      {
        subTopic: "Programming",
        items: [
          "Android Development",
          "Coding",
          "Flutter",
          "Frontend Engineering",
          "iOS Development",
          "Mobile Development",
          "Software Engineering",
          "Web Development",
        ],
      },
      {
        subTopic: "Programming Languages",
        items: [
          "Angular",
          "CSS",
          "HTML",
          "Java",
          "JavaScript",
          "NodeJS",
          "Python",
          "React",
          "TypeScript",
          "VueJS",
          "Ruby",
          "Ruby on Rails",
          "Swift",
        ],
      },
      {
        subTopic: "Dev Ops",
        items: ["AWS", "Databricks", "Docker", "Kubernetes", "Terraform"],
      },
      {
        subTopic: "Software Testing",
        items: [
          "Automated Testing",
          "Integration Testing",
          "Manual Testing",
          "Performance Testing",
          "Regression Testing",
          "Unit Testing",
        ],
      },
      {
        subTopic: "Operating System",
        items: ["Linux", "MacOS", "Windows", "Unix", "Android", "iOS"],
      },
    ],
  },
  {
    topic: "Media",
    subTopics: [
      {
        subTopic: "Writing",
        items: [
          "30 Day Challenge",
          "Book Reviews",
          "Books",
          "Creative Nonfiction",
          "Diary",
          "Fiction",
          "Haiku",
          "Hello World",
          "Memoir",
          "Nonfiction",
          "Personal Essay",
          "Poetry",
          "Screenwriting",
          "Short Stories",
          "This Happened To Me",
          "Writing Prompts",
          "Writing Tips",
        ],
      },
      {
        subTopic: "Art",
        items: [
          "Comics",
          "Contemporary Art",
          "Drawing",
          "Fine Art",
          "Generative Art",
          "Illustration",
          "Painting",
          "Portrait",
          "Street Art",
        ],
      },
      {
        subTopic: "Gaming",
        items: [
          "Game Design",
          "Game Development",
          "Indie Game",
          "Metaverse",
          "Nintendo",
          "Playstation",
          "Video Games",
          "Virtual Reality",
          "Xbox",
        ],
      },
    ],
  },
  {
    topic: "Society",
    subTopics: [
      {
        subTopic: "Economics",
        items: ["Basic Income", "Debt", "Economy", "Inflation", "Stock Market"],
      },
      {
        subTopic: "Education",
        items: [
          "Charter Schools",
          "Education Reform",
          "Higher Education",
          "PhD",
          "Public Schools",
          "Student Loans",
          "Stydy Abroad",
          "Teaching",
        ],
      },
      {
        subTopic: "Equality",
        items: [
          "Disability",
          "Discrimination",
          "Diversity In Tech",
          "Feminism",
          "Inclusion",
          "LGBTQIA",
          "Sexism",
          "Transgender",
          "Women Rights",
        ],
      },
      {
        subTopic: "Finance",
        items: [
          "401k",
          "Investing",
          "Money",
          "Philanthropy",
          "Real Estate",
          "Retirement",
        ],
      },
      {
        subTopic: "Law",
        items: [
          "Criminal Justice",
          "Law School",
          "Legaltech",
          "Social Justice",
          "Supreme Court",
        ],
      },
      {
        subTopic: "Transportation",
        items: [
          "Logistics",
          "Public Transit",
          "Self Driving Cars",
          "Trucking",
          "Urban Planning",
        ],
      },
      {
        subTopic: "Politics",
        items: [
          "Elections",
          "Government",
          "Gun Control",
          "Immigration",
          "Political Parties",
        ],
      },
      {
        subTopic: "Race",
        items: [
          "American Indian",
          "Anti Racism",
          "Asian American",
          "Black Lives Matter",
          "Indigenous People",
          "Multiracial",
          "Pacific Islander",
          "White Privilege",
          "White Supremacy",
        ],
      },
      {
        subTopic: "Science",
        items: [
          "Archaeology",
          "Astronomy",
          "Astrophysics",
          "Biotechnology",
          "Chemistry",
          "Ecology",
          "Genetics",
          "Geology",
          "Medicine",
          "Neuroscience",
          "Physics",
          "Psychology",
          "Space",
        ],
      },
      {
        subTopic: "Mathematics",
        items: ["Algebra", "Calculus", "Geometry", "Probability", "Statistics"],
      },
      {
        subTopic: "Drugs",
        items: [
          "Addiction",
          "Cannabis",
          "Opioids",
          "Pharmaceuticals",
          "Psychedelics",
        ],
      },
    ],
  },
  {
    topic: "Culture",
    subTopics: [
      {
        subTopic: "Philosophy",
        items: [
          "Atheism",
          "Epistemology",
          "Ethics",
          "Existentialism",
          "Metaphysics",
          "Morality",
          "Philosophy Of Mind",
          "Stoicism",
        ],
      },
      {
        subTopic: "Religion",
        items: [
          "Buddhism",
          "Christianity",
          "Hinduism",
          "Islam",
          "Judaism",
          "Zen",
        ],
      },
      {
        subTopic: "Spirituality",
        items: [
          "Astrology",
          "Energy Healing",
          "Horoscopes",
          "Mysticism",
          "Reiki",
        ],
      },
      {
        subTopic: "Cultural Studies",
        items: [
          "Ancient History",
          "Anthropology",
          "Cultural Heritage",
          "Digital Life",
          "History",
          "Museums",
          "Sociology",
          "Tradition",
        ],
      },
      {
        subTopic: "Fashion",
        items: [
          "Clothing",
          "Fashion Design",
          "Fashion Trends",
          "Shoes",
          "Sneakers",
          "Style",
        ],
      },
      {
        subTopic: "Beauty",
        items: ["Beauty Tips", "Body Image", "Hair", "Makeup", "Skincare"],
      },
      {
        subTopic: "Language",
        items: [
          "Arabic",
          "English Language",
          "English Learning",
          "French",
          "German",
          "Hindi",
          "Language Learning",
          "Linguistics",
          "Mandarin",
          "Portuguese",
          "Spanish",
        ],
      },
      {
        subTopic: "Sports",
        items: [
          "Baseball",
          "Basketball",
          "Football",
          "NBA",
          "NFL",
          "Premier League",
          "Soccer",
          "World Cup",
        ],
      },
    ],
  },
  {
    topic: "World",
    subTopics: [
      {
        subTopic: "Cities",
        items: [
          "Abu Dhabi",
          "Amsterdam",
          "Athens",
          "Bangkok",
          "Barcelona",
          "Berlin",
          "Boston",
          "Buenos Aires",
          "Chicago",
          "Copenhagen",
          "Delhi",
          "Dubai",
          "Dublin",
          "Edinburgh",
          "Glasgow",
          "Hong Kong",
          "Istanbul",
          "Lisbon",
          "London",
          "Los Angeles",
          "Madrid",
          "Melbourne",
          "Mexico City",
          "Miami",
          "Montreal",
          "New York City",
          "Paris",
          "Prague",
          "Rio De Janeiro",
          "Rome",
          "San Francisco",
          "Sydney",
          "Taipei",
          "Tel Aviv",
          "Tokyo",
          "Toronto",
          "Vancouver",
          "Vienna",
          "Delhi",
          "Mumbai",
          "Banglore",
          "Chennai",
          "Kolkata",
          "Surat",
          "Bhopal",
          "Indore",
        ],
      },
      {
        subTopic: "Nature",
        items: [
          "Birding",
          "Camping",
          "Climate Change",
          "Conservation",
          "Hiking",
          "Sustainability",
          "Wildlife",
        ],
      },
      {
        subTopic: "Travel",
        items: [
          "Tourism",
          "Travel Tips",
          "Travel Writing",
          "Vacation",
          "Vanlife",
        ],
      },
    ],
  },
];
