// Note: Do not edit this file. Before making chages in errorTypes.ts file in server

export const RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const BAD_REQUEST = "BAD_REQUEST";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";
export const INVALID_TOKEN = "INVALID_TOKEN";
export const AXIOS_ERROR = "AXIOS_ERROR";
